/**
 * REMOVED — this file is intentionally empty.
 *
 * The portal previously called the Google Calendar API directly via a service
 * account. Frontline has no Google Cloud project available, so scheduling is
 * now delegated to monday.com's own Google Calendar integration, configured
 * once in the monday UI on the Leadership 1:1 Sessions board.
 *
 * The app's responsibility is to populate the columns that integration reads:
 *   - item name        → event title
 *   - Meeting          → start time (written in UTC, see lib/scheduling.ts)
 *   - Attendees        → guest list
 *   - Event Description→ prep notes and the sign-off form link
 *
 * A prefilled "Add to Google Calendar" link is generated by
 * googleCalendarLink() in lib/scheduling.ts as a manual backup.
 */

export {};
